//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int no { get; set; }
        public string ıp { get; set; }
        public string tarayici { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string metot { get; set; }
        public string parametre { get; set; }
    }
}
